name: secure_compressor
description: "This is a Dart package that provides utilities for securely
  encrypting, decrypting, compressing, and decompressing string data using AES
  encryption and gzip compression"
version: 1.0.5
homepage: https://github.com/anonimeact/secure-compressor

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  share_plus: ^10.1.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  path_provider_platform_interface: ^2.0.2

platforms:
  ? android
  ? ios
  ? linux
  ? macos
  ? web
  ? windows
